export const TOGGLE_PRODUCT = 'TOGGLE_PRODUCT';
export const TOGGLE_CATEGORY = 'TOGGLE_CATEGORY';
export const TOGGLE_CART = 'TOGGLE_CART';
export const FETCH_PRODUCTS_LIST = 'FETCH_PRODUCTS_LIST';
export const FETCH_CATEGORIES_LIST = 'FETCH_CATEGORIES_LIST';

export const ADD_CART_ITEM = 'ADD_CART_ITEM';
export const BUY_CART = 'BUY_CART';

export const CLOTHES = 'CLOTHES';
export const FOOD = 'FOOD';
export const ELECTRICS = 'ELECTRICS';