export const TOGGLE_PRODUCT = 'TOGGLE_PRODUCT';
export const TOGGLE_CATEGORY = 'TOGGLE_CATEGORY';
export const FETCH_PRODUCTS_LIST = 'FETCH_PRODUCTS_LIST';
export const FETCH_CATEGORIES_LIST = 'FETCH_CATEGORIES_LIST';

export const CLOTHES = 'CLOTHES';
export const FOOD = 'FOOD';
export const ELECTRICS = 'ELECTRICS';